import { FormEvent, KeyboardEvent, useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import audioWorkletUrl from "./audio-worklet.ts?url";

type AppState = "idle" | "connecting" | "listening" | "translating" | "running" | "questioning" | "completed" | "failed";
type Message = { id: number; kind: "user" | "bot"; text: string; progress?: boolean };

const labels: Record<AppState, string> = { idle: "Ready", connecting: "Connecting", listening: "Listening", translating: "Translating", running: "Working", questioning: "Needs your answer", completed: "Complete", failed: "Needs attention" };
const friendlyError = (message: string) => /API_KEY|not configured/i.test(message) ? "Bolo needs its API keys configured before it can run this task." : message || "Something went wrong.";

function App() {
  const [state, setState] = useState<AppState>("idle");
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState<Message[]>([]);
  const [run, setRun] = useState<any>(null);
  const [recording, setRecording] = useState<{ label: string; seconds: number } | null>(null);
  const [shortcutVisible, setShortcutVisible] = useState(() => !localStorage.getItem("bolo:seenShortcutHint"));
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const conversationRef = useRef<HTMLElement>(null);
  const runId = useRef(""); const voiceSessionId = useRef(""); const voicePurpose = useRef("command");
  const mediaStream = useRef<MediaStream | null>(null); const audioContext = useRef<AudioContext | null>(null);
  const workletNode = useRef<AudioWorkletNode | null>(null); const silentGain = useRef<GainNode | null>(null);
  const pollTimer = useRef<ReturnType<typeof setTimeout> | null>(null); const recordingTimer = useRef<ReturnType<typeof setInterval> | null>(null);
  const recordingStartedAt = useRef(0); const handledQuestionId = useRef(""); const messageId = useRef(0);
  const speechAudio = useRef<HTMLAudioElement | null>(null); const speechUrl = useRef(""); const speechGeneration = useRef(0); const speechFinish = useRef<(() => void) | null>(null);

  const addMessage = (kind: Message["kind"], text: string, progress = false) => setMessages((items) => [...items, { id: ++messageId.current, kind, text, progress }]);
  const clearPoll = () => { if (pollTimer.current) clearTimeout(pollTimer.current); };
  const stopSpeech = () => { speechGeneration.current++; speechAudio.current?.pause(); speechFinish.current?.(); if (speechUrl.current) URL.revokeObjectURL(speechUrl.current); speechUrl.current = ""; speechAudio.current = null; speechFinish.current = null; };
  const finishProgress = (label: string) => setRun((value: any) => value ? { ...value, progress: label, finished: true } : value);
  const fail = (message: string) => { clearPoll(); setState("failed"); finishProgress("Stopped"); addMessage("bot", friendlyError(message)); };
  const canAnswer = state === "questioning" || (voicePurpose.current === "answer" && Boolean(run?.pendingQuestion) && ["connecting", "listening", "translating"].includes(state));
  const idleLike = ["idle", "completed", "failed"].includes(state); const canInput = idleLike || canAnswer;

  useEffect(() => { document.body.classList.toggle("is-listening", ["connecting", "listening", "translating"].includes(state)); document.body.classList.toggle("is-working", state === "running"); document.body.classList.toggle("is-attention", ["questioning", "failed"].includes(state)); }, [state]);
  useEffect(() => { if (messages.length) { window.boloDesktop.setExpanded(true); requestAnimationFrame(() => { if (conversationRef.current) conversationRef.current.scrollTop = conversationRef.current.scrollHeight; }); } }, [messages]);
  useEffect(() => { const unVoice = window.boloDesktop.onVoiceEvent(handleVoiceEvent); const unFocus = window.boloDesktop.onFocusCommand(() => { inputRef.current?.focus(); setShortcutVisible(false); localStorage.setItem("bolo:seenShortcutHint", "1"); }); const unNew = window.boloDesktop.onNewCommand(resetTask); const onKeyDownGlobal = (event: globalThis.KeyboardEvent) => { if (event.key === "Escape") window.boloDesktop.hideWindow(); }; window.addEventListener("focus", focusInput); window.addEventListener("keydown", onKeyDownGlobal); return () => { unVoice?.(); unFocus?.(); unNew?.(); window.removeEventListener("focus", focusInput); window.removeEventListener("keydown", onKeyDownGlobal); clearPoll(); }; }, [run, state]);
  const focusInput = () => inputRef.current?.focus();
  const speak = async (text: string, languageCode = "en-IN") => { if (!text.trim()) return; stopSpeech(); const generation = ++speechGeneration.current; try { const bytes = await window.boloDesktop.speech(text, languageCode); if (generation !== speechGeneration.current) return; speechUrl.current = URL.createObjectURL(new Blob([bytes], { type: "audio/wav" })); const audio = new Audio(speechUrl.current); speechAudio.current = audio; await new Promise<void>((resolve, reject) => { speechFinish.current = resolve; audio.addEventListener("ended", resolve, { once: true }); audio.addEventListener("error", reject, { once: true }); audio.play().catch(reject); }); } catch { /* Spoken response is optional. */ } finally { if (speechUrl.current) URL.revokeObjectURL(speechUrl.current); speechUrl.current = ""; speechAudio.current = null; speechFinish.current = null; } };
  const schedulePoll = (delay = 400) => { clearPoll(); pollTimer.current = setTimeout(pollRun, delay); };
  const pollRun = async () => { if (!runId.current) return; try { const nextRun = await window.boloDesktop.getRun(runId.current); setRun(nextRun); if (nextRun.state === "completed") { setState("completed"); finishProgress("Task complete"); addMessage("bot", nextRun.result || "The task is complete."); await speak(nextRun.result || "The task is complete.", nextRun.languageCode || "en-IN"); return; } if (["failed", "cancelled"].includes(nextRun.state)) return fail(nextRun.error || "The task stopped."); if (nextRun.state === "waiting_for_user" && nextRun.pendingQuestion) { setState("questioning"); if (handledQuestionId.current !== nextRun.pendingQuestion.id) { handledQuestionId.current = nextRun.pendingQuestion.id; addMessage("bot", nextRun.pendingQuestion.prompt); await speak(nextRun.pendingQuestion.prompt, nextRun.languageCode || "en-IN"); if (runId.current) await startRecording("answer", nextRun.pendingQuestion.id); } } else setState("running"); schedulePoll(); } catch (error: any) { fail(`Lost contact with the task. ${error.message}`); } };
  const cleanupRecording = () => { if (recordingTimer.current) clearInterval(recordingTimer.current); setRecording(null); workletNode.current?.disconnect(); silentGain.current?.disconnect(); mediaStream.current?.getTracks().forEach((track) => track.stop()); audioContext.current?.close().catch(() => {}); workletNode.current = null; silentGain.current = null; mediaStream.current = null; audioContext.current = null; };
  const cancelRecording = async () => { const id = voiceSessionId.current; voiceSessionId.current = ""; cleanupRecording(); if (id) try { await window.boloDesktop.cancelVoice(id); } catch {} setState(voicePurpose.current === "answer" ? "questioning" : "idle"); };
  const startRecording = async (purpose = "command", questionId: string | null = null) => { if (voiceSessionId.current) return; try { stopSpeech(); mediaStream.current = await navigator.mediaDevices.getUserMedia({ audio: { channelCount: 1, echoCancellation: true, noiseSuppression: true, autoGainControl: true } }); audioContext.current = new AudioContext(); await audioContext.current.audioWorklet.addModule(audioWorkletUrl); workletNode.current = new AudioWorkletNode(audioContext.current, "bolo-pcm-processor"); silentGain.current = audioContext.current.createGain(); silentGain.current.gain.value = 0; audioContext.current.createMediaStreamSource(mediaStream.current).connect(workletNode.current); workletNode.current.connect(silentGain.current); silentGain.current.connect(audioContext.current.destination); voicePurpose.current = purpose; const started = await window.boloDesktop.startVoice({ purpose, ...(purpose === "answer" ? { runId: runId.current, questionId } : {}) }); voiceSessionId.current = started.sessionId; workletNode.current.port.onmessage = (event) => { if (voiceSessionId.current && event.data?.byteLength) window.boloDesktop.sendVoiceChunk(voiceSessionId.current, event.data); }; recordingStartedAt.current = Date.now(); setRecording({ label: purpose === "answer" ? "Listening for your answer" : "Listening", seconds: 0 }); recordingTimer.current = setInterval(() => setRecording((value) => value && { ...value, seconds: Math.floor((Date.now() - recordingStartedAt.current) / 1000) }), 500); setState("connecting"); } catch (error: any) { cleanupRecording(); fail(error.name === "NotAllowedError" ? "Microphone access is off. Allow it in System Settings or type the task." : `The microphone could not start: ${error.message}`); } };
  const handleVoiceEvent = (event: any) => { if (!event || event.sessionId !== voiceSessionId.current) return; if (["ready", "speech-start"].includes(event.type)) setState("listening"); else if (event.type === "speech-end") setState("translating"); else if (event.type === "translated") { voiceSessionId.current = ""; cleanupRecording(); addMessage("user", event.transcript); if (voicePurpose.current === "command") runId.current = event.runId; setState("running"); setRun({ progress: "Working", toolActivity: [] }); schedulePoll(0); } else if (event.type === "failed") { voiceSessionId.current = ""; cleanupRecording(); if (voicePurpose.current === "answer" && run?.pendingQuestion) { addMessage("bot", friendlyError(event.error)); setState("questioning"); } else fail(event.error); } else if (event.type === "closed") { voiceSessionId.current = ""; cleanupRecording(); } };
  const submitText = async (text: string) => { const value = text.trim(); if (!value) return; setInput(""); addMessage("user", value); try { if (run?.pendingQuestion) { if (voiceSessionId.current) await cancelRecording(); await window.boloDesktop.answerRun(runId.current, run.pendingQuestion.id, value); setState("running"); schedulePoll(0); return; } if (["completed", "failed"].includes(state)) resetTask(); const started = await window.boloDesktop.startAgent(value); runId.current = started.id; setState("running"); setRun({ progress: "Working", toolActivity: [] }); schedulePoll(0); } catch (error: any) { fail(error.message); } };
  const stopEverything = async () => { stopSpeech(); if (voiceSessionId.current) await cancelRecording(); if (runId.current) try { await window.boloDesktop.stopRun(runId.current); } catch {} fail("Stopped by the user."); };
  function resetTask() { clearPoll(); stopSpeech(); if (voiceSessionId.current) void cancelRecording(); runId.current = ""; handledQuestionId.current = ""; setRun(null); setMessages([]); setInput(""); window.boloDesktop.setExpanded(false); setState("idle"); requestAnimationFrame(focusInput); }
  const onKeyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void submitText(input); } };
  const adjustHeight = (target: HTMLTextAreaElement) => { target.style.height = "auto"; target.style.height = `${Math.min(target.scrollHeight, 92)}px`; };
  const onSubmit = (event: FormEvent) => { event.preventDefault(); void submitText(input); };
  return <main className="palette" aria-label="Bolo execution agent"><section ref={conversationRef} className="conversation" hidden={!messages.length}><div className="chat-log" aria-live="polite">{messages.map((message) => <article className={`message ${message.kind}`} key={message.id}><span className="message-label">{message.kind === "user" ? "You" : "Bolo"}</span><div className="message-body">{message.progress ? <Progress run={run} onStop={stopEverything} /> : message.text}</div></article>)}{run && !messages.some((message) => message.progress) && <article className="message bot"><span className="message-label">Bolo</span><div className="message-body"><Progress run={run} onStop={stopEverything} /></div></article>}</div></section>{recording && <section className="recording-bar"><span className="recording-pulse" /><strong>{recording.label}</strong><span>{Math.floor(recording.seconds / 60)}:{String(recording.seconds % 60).padStart(2, "0")}</span><button className="quiet-button" type="button" onClick={() => void cancelRecording()}>Cancel</button></section>}<form className="composer" onSubmit={onSubmit}><span className="composer-orb" aria-hidden="true"><i /></span><textarea ref={inputRef} rows={1} maxLength={4000} value={input} disabled={!canInput} onChange={(event) => { setInput(event.target.value); adjustHeight(event.target); }} onKeyDown={onKeyDown} placeholder={canAnswer ? "Type your answer…" : "What do you want to get done?"} aria-label="Task or answer" /><button className="icon-button" type="button" disabled={!canInput} onClick={() => void startRecording(state === "questioning" ? "answer" : "command", run?.pendingQuestion?.id || null)} aria-label="Start a voice request" title="Start voice"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 14.5a3.5 3.5 0 0 0 3.5-3.5V6.5a3.5 3.5 0 1 0-7 0V11a3.5 3.5 0 0 0 3.5 3.5Zm6-3.5a6 6 0 0 1-12 0M12 17v3.5M8.5 20.5h7" /></svg></button><button className="send-button" type="submit" hidden={!input.trim() || !canInput} aria-label={canAnswer ? "Send answer" : "Run task"}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 14-7-4 14-3.5-5.5L5 12Z" /></svg></button></form>{shortcutVisible && <footer className="shortcut-hint"><kbd>⌘</kbd><kbd>⇧</kbd><kbd>Space</kbd> to show Bolo</footer>}<p className="sr-only" aria-live="polite">Bolo is {labels[state].toLowerCase()}.</p></main>;
}

function Progress({ run, onStop }: { run: any; onStop: () => void }) { return <div className="progress-card"><div className="progress-row">{!run?.finished && <span className="spinner" aria-hidden="true" />}<strong>{run?.progress || "Working"}</strong><button className="stop-button" type="button" disabled={run?.finished} onClick={() => void onStop()}>Stop</button></div>{Boolean(run?.toolActivity?.length) && <ol className="progress-steps">{run.toolActivity.map((item: any, index: number) => <li key={`${item.tool}-${index}`}>{item.tool}: {item.detail}</li>)}</ol>}</div>; }

createRoot(document.getElementById("root")!).render(<App />);
